#This needs to go or to be handled in the proper way
ROUT = "ROUT"
RCR = "RCR"
RCT = "RCT"
RCL = "RCL"
RCB = "RCB"
CONST = "CONST"
LWD = "LWD"
ADD = "ADD"
NOP = "NOP"
SWD = "SWD"
ZERO = "ZERO"
ONE = "ONE"